"""create tables

Revision ID: d7890fc7df8d
Revises: 
Create Date: 2025-09-25 15:31:47.145671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7890fc7df8d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('LENGTH(email) >= 6', name='ck_user_email_len_ge_6'),
    sa.CheckConstraint('LENGTH(username) >= 3', name='ck_user_username_len_ge_3'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email', name='uq_user_email'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('username', name='uq_user_username')
    )
    op.create_table('profiles',
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('bio', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('LENGTH(bio) >= 1', name='ck_profile_bio_len_ge_1'),
    sa.CheckConstraint('LENGTH(first_name) >= 1', name='ck_profile_first_name_len_ge_1'),
    sa.CheckConstraint('LENGTH(last_name) >= 1', name='ck_profile_last_name_len_ge_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    op.drop_table('users')
    # ### end Alembic commands ###
