"""create users_codes table

Revision ID: f303454712a1
Revises: 5d973566cc68
Create Date: 2025-09-27 14:42:12.093296

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f303454712a1"
down_revision: Union[str, Sequence[str], None] = "5d973566cc68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_codes",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=6), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.CheckConstraint("LENGTH(code) = 6", name="ck_user_code_code_len_eq_6"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", name="uq_user_code_user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_codes")
    # ### end Alembic commands ###
